steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '--recurse-submodules', 'https://github.com/Kovalevskyi-Academy/testing-framework.git']
  - name: 'gcr.io/cloud-builders/git'
    args: ['checkout', '$COMMIT_SHA']
    dir: 'testing-framework'
  - name: 'maven:3.6.3-openjdk-15'
    args: ['mvn', '-Dmaven.wagon.http.retryHandler.count=3', 'compile']
    dir: 'testing-framework'
  - name: 'maven:3.6.3-openjdk-15'
    args: [ 'mvn', '-Dmaven.wagon.http.retryHandler.count=3', 'test' ]
    dir: 'testing-framework'
  - name: 'maven:3.6.3-openjdk-15'
    args: [ 'mvn', '-Dmaven.wagon.http.retryHandler.count=3', 'package' ]
    dir: 'testing-framework'
  - name: 'maven:3.6.3-openjdk-15'
    args: [ 'mvn', '-Dmaven.wagon.http.retryHandler.count=3', 'deploy' ]
    dir: 'testing-framework'